# Generated by Django 3.0.7 on 2020-06-18 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 23, 40, 21, 974679), verbose_name='Thời gian khám'),
        ),
    ]
