# Generated by Django 3.0.7 on 2020-06-19 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0002_auto_20200618_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 19, 10, 59, 23, 197640), verbose_name='Thời gian khám'),
        ),
    ]
