# Generated by Django 3.0.7 on 2020-06-20 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0003_auto_20200619_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 20, 18, 46, 24, 407590), verbose_name='Thời gian khám'),
        ),
    ]
