# Generated by Django 3.0.7 on 2020-06-20 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0004_auto_20200620_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 20, 19, 2, 41, 591386), verbose_name='Thời gian khám'),
        ),
    ]
