# Generated by Django 3.0.7 on 2020-06-21 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0005_auto_20200620_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 11, 29, 26, 895690), verbose_name='Thời gian khám'),
        ),
    ]
