# Generated by Django 3.0.7 on 2020-06-21 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0006_auto_20200621_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 18, 3, 0, 791325), verbose_name='Thời gian khám'),
        ),
    ]
