# Generated by Django 3.0.7 on 2020-06-22 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0007_auto_20200621_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='imp_diagnosis',
            field=models.CharField(default='', max_length=512, verbose_name='Chẩn đoán xác định'),
        ),
        migrations.AddField(
            model_name='examination',
            name='pre_diagnosis',
            field=models.CharField(default='', max_length=512, verbose_name='Chẩn đoán sơ bộ'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 22, 14, 0, 25, 629117), verbose_name='Thời gian khám'),
        ),
    ]
