# Generated by Django 3.0.7 on 2020-06-23 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0009_auto_20200622_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 23, 11, 51, 51, 990737), verbose_name='Thời gian khám'),
        ),
    ]
