# Generated by Django 3.0.7 on 2020-06-23 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0010_auto_20200623_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 23, 11, 56, 43, 299340), verbose_name='Thời gian khám'),
        ),
    ]
