# Generated by Django 3.0.7 on 2020-06-18 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testName', models.CharField(max_length=64, verbose_name='Tên xét nghiệm')),
                ('testType', models.CharField(choices=[('Blood test', 'Blood Test'), ('Other test', 'Other Test')], default='Blood test', max_length=64, verbose_name='Loại xét nghiệm')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_test_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
