# Generated by Django 3.0.7 on 2020-06-23 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0010_auto_20200623_1151'),
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='examination',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treatment', to='examination.Examination'),
        ),
    ]
