# Generated by Django 3.0.7 on 2020-06-19 03:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treatment', '0001_initial'),
        ('medication', '0002_auto_20200614_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='treatment.Treatment')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medication.Medication')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_list', to='prescription.Prescription')),
            ],
        ),
    ]
