# Generated by Django 3.0.2 on 2020-06-13 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Họ tên')),
                ('address', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('contact', models.CharField(max_length=64, verbose_name='Liên lạc')),
                ('ssid', models.CharField(max_length=32, verbose_name='Mã an sinh xã hội')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_author', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
