export const MEDICATION = "MEDICATION";
export const PATIENT = "PATIENT";
export const RECORD = "RECORD";
export const APPOINTMENT = "APPOINTMENT";

export const MEDICATION_REDUX_TYPE = {
    CREATE: "MEDICATION_CREATE",
    UPDATE: "MEDICATION_UPDATE",
    DELETE: "MEDICATION_DELETE",
    DETAIL: "MEDICATION_DETAIL",
    FETCH: "MEDICATION_FETCH",
};
export const PATIENT_REDUX_TYPE = {
    CREATE: "PATIENT_CREATE",
    UPDATE: "PATIENT_UPDATE",
    DELETE: "PATIENT_DELETE",
    DETAIL: "PATIENT_DETAIL",
    FETCH: "PATIENT_FETCH",
};
export const RECORD_REDUX_TYPE = {
    CREATE: "RECORD_CREATE",
    UPDATE: "RECORD_UPDATE",
    DELETE: "RECORD_DELETE",
    DETAIL: "RECORD_DETAIL",
    FETCH: "RECORD_FETCH",
};
export const APPOINTMENT_REDUX_TYPE = {
    CREATE: "APPOINTMENT_CREATE",
    UPDATE: "APPOINTMENT_UPDATE",
    DELETE: "APPOINTMENT_DELETE",
    DETAIL: "APPOINTMENT_DETAIL",
    FETCH: "APPOINTMENT_FETCH",
};