# Generated by Django 3.0.2 on 2020-06-13 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='start time')),
                ('address', models.CharField(default='', max_length=255)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('HAPPENING', 'Happening'), ('END', 'End')], default='WAITING', max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_author', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='doctor.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='patient.Patient')),
            ],
        ),
    ]
