# Generated by Django 3.0.7 on 2020-06-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20200617_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.DateTimeField(verbose_name='Thời gian bắt đầu'),
        ),
    ]
