# Generated by Django 3.0.2 on 2020-06-13 09:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Tên thuốc')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tên thuốc')),
                ('companyName', models.CharField(max_length=256, verbose_name='Công ty sản xuất')),
                ('description', models.CharField(max_length=2048, verbose_name='Mô tả')),
                ('medicationGuide', models.CharField(max_length=256, verbose_name='Hướng dẫn sử dụng')),
                ('medicationType', models.CharField(max_length=32, verbose_name='Loại thuốc')),
                ('notion', models.CharField(max_length=256, verbose_name='Lưu ý')),
                ('isFreeBuy', models.BooleanField(default=True, verbose_name='Được mua tự do')),
                ('isFinedMedication', models.BooleanField(default=False, verbose_name='Loại ổn định giá')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
