# Generated by Django 3.0.2 on 2020-06-14 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='medicationType',
            field=models.CharField(max_length=256, verbose_name='Loại thuốc'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số lượng'),
        ),
    ]
