# Generated by Django 3.0.7 on 2020-06-18 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examination', '0001_initial'),
        ('basictest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(default='', max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('basic_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_test', to='basictest.BasicTest')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case_author', to=settings.AUTH_USER_MODEL)),
                ('examinations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcase', to='examination.Examination')),
            ],
        ),
    ]
