# Generated by Django 3.0.7 on 2020-06-18 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testcase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='examinations',
            new_name='examination',
        ),
    ]
